[[redirects]]
  from = "/"
  to = "/api-reference/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/api-reference/introduction"
  status = 301
  force = true

 